name = "blue"
compatibility_date = "2022-12-31"

account_id = "a749f4459c0e24f9b878279b7a63edbf" # â† Replace with your Account ID.
workers_dev = true

[[ d1_databases ]]
binding = "DB"
database_name = "blue"
database_id = "8c429ae5-dc4c-4b32-ab19-6767a517551f"

[[ d1_databases ]]
binding = "DB"
database_name = "blue_development"
database_id = "ecdc9bd0-bf68-4921-8e03-8d7a9793593d"

[[r2_buckets]]
binding = 'FILE_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'blue'
preview_bucket_name = 'development'
